import { useEffect, useState } from 'react';
import { Pencil, Plus, X } from 'lucide-react';
import { storage } from './storage';
import type { InventoryCategory, InventoryItem } from './types';

const categories:InventoryCategory[]=['Phone','Accessory','Prepaid Service','Repair Part'];
const splitTags=(value:string)=>value.split(',').map(x=>x.trim()).filter(Boolean);
const joinTags=(value?:string[])=>value?.join(', ')||'';

export default function InventoryManagerWidget(){
 const [visible,setVisible]=useState(false),[open,setOpen]=useState(false),[editingId,setEditingId]=useState('');
 const [category,setCategory]=useState<InventoryCategory>('Phone'),[name,setName]=useState(''),[brand,setBrand]=useState(''),[model,setModel]=useState(''),[sku,setSku]=useState(''),[barcode,setBarcode]=useState('');
 const [imei,setImei]=useState(''),[serial,setSerial]=useState(''),[carrier,setCarrier]=useState(''),[storageSize,setStorageSize]=useState(''),[color,setColor]=useState(''),[condition,setCondition]=useState<InventoryItem['condition']>('New'),[batteryHealth,setBatteryHealth]=useState('');
 const [quantity,setQuantity]=useState('1'),[minimum,setMinimum]=useState('1'),[cost,setCost]=useState(''),[price,setPrice]=useState(''),[notes,setNotes]=useState('');
 const [repairDeviceType,setRepairDeviceType]=useState('Cellphone Repair'),[compatibleBrands,setCompatibleBrands]=useState(''),[compatibleModels,setCompatibleModels]=useState(''),[compatibleRepairTypes,setCompatibleRepairTypes]=useState('');
 const [warranty,setWarranty]=useState('30 Day Store Warranty'),[supplier,setSupplier]=useState(''),[location,setLocation]=useState('');

 function clearForm(){setEditingId('');setCategory('Phone');setName('');setBrand('');setModel('');setSku('');setBarcode('');setImei('');setSerial('');setCarrier('');setStorageSize('');setColor('');setCondition('New');setBatteryHealth('');setQuantity('1');setMinimum('1');setCost('');setPrice('');setNotes('');setRepairDeviceType('Cellphone Repair');setCompatibleBrands('');setCompatibleModels('');setCompatibleRepairTypes('');setWarranty('30 Day Store Warranty');setSupplier('');setLocation('')}
 function close(){setOpen(false);clearForm()}
 function startEdit(item:InventoryItem){setEditingId(item.id);setCategory(item.category);setName(item.name||'');setBrand(item.brand||'');setModel(item.model||'');setSku(item.sku||'');setBarcode(item.barcode||'');setImei(item.imei||'');setSerial(item.serial||'');setCarrier(item.carrier||'');setStorageSize(item.storage||'');setColor(item.color||'');setCondition(item.condition||'New');setBatteryHealth(item.batteryHealth==null?'':String(item.batteryHealth));setQuantity(String(item.quantity||0));setMinimum(String(item.minimum||0));setCost(String(item.cost||0));setPrice(String(item.price||0));setNotes(item.notes||'');setRepairDeviceType(item.repairDeviceType||'Cellphone Repair');setCompatibleBrands(joinTags(item.compatibleBrands));setCompatibleModels(joinTags(item.compatibleModels));setCompatibleRepairTypes(joinTags(item.compatibleRepairTypes));setWarranty(item.warranty||'30 Day Store Warranty');setSupplier(item.supplier||'');setLocation(item.location||'');setOpen(true)}

 useEffect(()=>{const openForm=()=>{clearForm();setOpen(true)};const editForm=(event:Event)=>{const id=(event as CustomEvent<{itemId?:string}>).detail?.itemId;const item=storage.getInventory().find(i=>i.id===id);if(item)startEdit(item)};const sync=()=>{setVisible(document.querySelector('.topbar h1')?.textContent?.trim()==='Inventory');document.querySelectorAll('.board-column').forEach(column=>{const title=column.querySelector('h3')?.textContent?.trim();if(title==='Quality Check'||title==='Completed')(column as HTMLElement).style.display='none'});document.querySelectorAll('.repair-card select').forEach(select=>Array.from(select.querySelectorAll('option')).forEach(option=>{if(option.textContent==='Quality Check'||option.textContent==='Completed')option.remove()}))};sync();const observer=new MutationObserver(sync);observer.observe(document.body,{subtree:true,childList:true,characterData:true});window.addEventListener('gadgetpos-data-changed',sync);window.addEventListener('gadgetpos-open-inventory-form',openForm);window.addEventListener('gadgetpos-edit-inventory-item',editForm as EventListener);return()=>{observer.disconnect();window.removeEventListener('gadgetpos-data-changed',sync);window.removeEventListener('gadgetpos-open-inventory-form',openForm);window.removeEventListener('gadgetpos-edit-inventory-item',editForm as EventListener)}},[]);

 function save(){if(!name.trim()){alert('Enter an item name.');return}if((Number(quantity)||0)<0||(Number(cost)||0)<0||(Number(price)||0)<0){alert('Quantity and prices cannot be negative.');return}if(category==='Repair Part'&&!compatibleModels.trim()){alert('Add at least one compatible model for this repair part.');return}const existing=storage.getInventory(),old=existing.find(i=>i.id===editingId);const item:InventoryItem={id:editingId||crypto.randomUUID(),category,name:name.trim(),brand:brand.trim()||undefined,model:model.trim()||undefined,sku:sku.trim()||undefined,barcode:barcode.trim()||undefined,imei:imei.trim()||undefined,serial:serial.trim()||undefined,carrier:carrier.trim()||undefined,storage:storageSize.trim()||undefined,color:color.trim()||undefined,condition:category==='Phone'?condition:undefined,batteryHealth:category==='Phone'&&batteryHealth?Number(batteryHealth):undefined,quantity:Number(quantity)||0,minimum:Number(minimum)||0,cost:Number(cost)||0,price:Number(price)||0,notes:notes.trim()||undefined,repairDeviceType:category==='Repair Part'?repairDeviceType:undefined,compatibleBrands:category==='Repair Part'?splitTags(compatibleBrands):undefined,compatibleModels:category==='Repair Part'?splitTags(compatibleModels):undefined,compatibleRepairTypes:category==='Repair Part'?splitTags(compatibleRepairTypes):undefined,warranty:category==='Repair Part'?warranty:undefined,supplier:supplier.trim()||undefined,location:location.trim()||undefined,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};storage.saveInventory(editingId?existing.map(i=>i.id===editingId?item:i):[item,...existing]);window.dispatchEvent(new Event('gadgetpos-data-changed'));alert(`${item.name} ${editingId?'updated':'added'} successfully.`);close()}

 return <>{visible&&<button className="inventory-add-button" onClick={()=>{clearForm();setOpen(true)}}><Plus size={17}/>Add Inventory Item</button>}{open&&<div className="inventory-modal-backdrop"><div className="inventory-modal"><div className="inventory-modal-head"><div><h2>{editingId?'Edit Inventory Item':'Add Inventory Item'}</h2><p>{category==='Repair Part'?'Tag this part to the exact devices and repairs it supports.':'Update phones, accessories, prepaid items, or repair parts.'}</p></div><button onClick={close} aria-label="Close"><X size={20}/></button></div><div className="inventory-form-grid">
  <label>Category<select value={category} onChange={e=>setCategory(e.target.value as InventoryCategory)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Item Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Brand<input value={brand} onChange={e=>setBrand(e.target.value)}/></label><label>Model / Description<input value={model} onChange={e=>setModel(e.target.value)}/></label><label>SKU<input value={sku} onChange={e=>setSku(e.target.value)}/></label><label>Barcode<input value={barcode} onChange={e=>setBarcode(e.target.value)}/></label>
  {category==='Phone'&&<><label>IMEI<input value={imei} onChange={e=>setImei(e.target.value)}/></label><label>Serial Number<input value={serial} onChange={e=>setSerial(e.target.value)}/></label><label>Carrier<input value={carrier} onChange={e=>setCarrier(e.target.value)}/></label><label>Storage<input value={storageSize} onChange={e=>setStorageSize(e.target.value)}/></label><label>Color<input value={color} onChange={e=>setColor(e.target.value)}/></label><label>Condition<select value={condition} onChange={e=>setCondition(e.target.value as InventoryItem['condition'])}><option>New</option><option>Like New</option><option>Good</option><option>Fair</option><option>For Parts</option></select></label><label>Battery Health %<input type="number" min="0" max="100" value={batteryHealth} onChange={e=>setBatteryHealth(e.target.value)}/></label></>}
  {category==='Repair Part'&&<><div className="inventory-section-title"><strong>Repair Compatibility</strong><span>Separate multiple choices with commas.</span></div><label>Device Type<select value={repairDeviceType} onChange={e=>setRepairDeviceType(e.target.value)}><option>Cellphone Repair</option><option>Tablet Repair</option><option>Computer Repair</option><option>Game Console Repair</option><option>Apple Watch Repair</option><option>Quick Check-in</option></select></label><label>Compatible Brand(s)<input value={compatibleBrands} onChange={e=>setCompatibleBrands(e.target.value)} placeholder="Apple, Samsung"/></label><label className="inventory-wide-field">Compatible Model(s)<textarea value={compatibleModels} onChange={e=>setCompatibleModels(e.target.value)} placeholder="iPhone 14, iPhone 14 Plus"/></label><label className="inventory-wide-field">Compatible Repair Type(s)<textarea value={compatibleRepairTypes} onChange={e=>setCompatibleRepairTypes(e.target.value)} placeholder="Screen Replacement, Display Replacement"/></label><label>Warranty<select value={warranty} onChange={e=>setWarranty(e.target.value)}><option>Lifetime Screen Warranty</option><option>90 Day Store Warranty</option><option>30 Day Store Warranty</option><option>No Warranty</option></select></label></>}
  <label>Supplier<input value={supplier} onChange={e=>setSupplier(e.target.value)}/></label><label>Shelf / Bin Location<input value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Quantity<input type="number" min="0" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Low-stock level<input type="number" min="0" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label><label>Cost<input type="number" min="0" step=".01" value={cost} onChange={e=>setCost(e.target.value)}/></label><label>Selling / Repair Price<input type="number" min="0" step=".01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="inventory-notes">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>
 </div><div className="inventory-modal-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={save}>{editingId?<><Pencil size={16}/>Save Changes</>:<><Plus size={16}/>Save Inventory Item</>}</button></div></div></div>}</>;
}
