import { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowUp, Eye, EyeOff, Pencil, Plus, Printer, Settings2, ShoppingCart, Trash2, X } from 'lucide-react';
import { storage } from './storage';
import type { InventoryItem, Repair, RepairStatus } from './types';

type Entry={id:string;name:string;hidden?:boolean};
type Catalog={categories:Entry[];brands:Record<string,Entry[]>;models:Record<string,Entry[]>;services:Record<string,Entry[]>};
type Step='brand'|'model'|'service'|'part'|'final';
type ManageLevel='category'|'brand'|'model'|'service';
const uid=()=>crypto.randomUUID();
const entries=(names:string[])=>names.map(name=>({id:uid(),name}));
const key=(...parts:string[])=>parts.join('::');
const norm=(value:string)=>value.trim().toLowerCase();
const CATEGORIES=['Cellphone Repair','Tablet Repair','Computer Repair','Game Console Repair','Apple Watch Repair','Quick Check-in'];
const BRANDS:Record<string,string[]>={
 'Cellphone Repair':['Apple','Samsung','Motorola','Google','Other'],
 'Tablet Repair':['Apple','Samsung','Amazon','Microsoft','Other'],
 'Computer Repair':['Apple','Windows PC','Chromebook','Other'],
 'Game Console Repair':['PlayStation','Xbox','Nintendo','Other'],
 'Apple Watch Repair':['Apple'],
 'Quick Check-in':['General Device']
};
const MODELS:Record<string,string[]>={
 [key('Cellphone Repair','Apple')]:['iPhone 16 Pro Max','iPhone 16 Pro','iPhone 16 Plus','iPhone 16','iPhone 15 Pro Max','iPhone 15 Pro','iPhone 15 Plus','iPhone 15','iPhone 14 Pro Max','iPhone 14 Pro','iPhone 14 Plus','iPhone 14','iPhone 13 Pro Max','iPhone 13 Pro','iPhone 13 Mini','iPhone 13','iPhone 12 Pro Max','iPhone 12 Pro','iPhone 12 Mini','iPhone 12','iPhone 11 Pro Max','iPhone 11 Pro','iPhone 11','iPhone XR','iPhone SE','Other iPhone'],
 [key('Cellphone Repair','Samsung')]:['Galaxy S25 Ultra','Galaxy S25+','Galaxy S25','Galaxy S24 Ultra','Galaxy S24+','Galaxy S24','Galaxy S23 Ultra','Galaxy S23+','Galaxy S23','Galaxy S22 Ultra','Galaxy S22+','Galaxy S22','Galaxy A15','Galaxy A14','Galaxy A13','Galaxy Z Fold','Galaxy Z Flip','Galaxy Note','Other Galaxy Phone'],
 [key('Cellphone Repair','Motorola')]:['Moto G Series','Moto Edge Series','Moto Razr','Other Motorola Phone'],
 [key('Cellphone Repair','Google')]:['Pixel 9 Series','Pixel 8 Series','Pixel 7 Series','Pixel 6 Series','Pixel Fold','Other Pixel'],
 [key('Cellphone Repair','Other')]:['OnePlus Phone','LG Phone','Nokia Phone','Other Cellphone'],
 [key('Tablet Repair','Apple')]:['iPad Pro 13-inch','iPad Pro 12.9-inch','iPad Pro 11-inch','iPad Air 13-inch','iPad Air 11-inch','iPad Air 5','iPad Air 4','iPad 10th Gen','iPad 9th Gen','iPad 8th Gen','iPad 7th Gen','iPad 6th Gen','iPad Mini 7','iPad Mini 6','iPad Mini 5','Other iPad'],
 [key('Tablet Repair','Samsung')]:['Galaxy Tab S10 Ultra','Galaxy Tab S10+','Galaxy Tab S9 Ultra','Galaxy Tab S9+','Galaxy Tab S9','Galaxy Tab S8 Ultra','Galaxy Tab S8+','Galaxy Tab S8','Galaxy Tab A9+','Galaxy Tab A9','Galaxy Tab A8','Galaxy Tab A7','Other Galaxy Tab'],
 [key('Tablet Repair','Amazon')]:['Fire Max 11','Fire HD 10','Fire HD 8','Fire 7','Fire Kids Pro','Other Fire Tablet'],
 [key('Tablet Repair','Microsoft')]:['Surface Pro 11','Surface Pro 10','Surface Pro 9','Surface Pro 8','Surface Go 4','Surface Go 3','Surface Book','Other Surface'],
 [key('Tablet Repair','Other')]:['Lenovo Tablet','Google Pixel Tablet','Onn Tablet','Other Tablet'],
 [key('Computer Repair','Apple')]:['MacBook Air 15-inch','MacBook Air 13-inch M-series','MacBook Air Intel','MacBook Pro 16-inch','MacBook Pro 14-inch','MacBook Pro 13-inch','iMac 24-inch','iMac 27-inch','Mac Mini','Mac Studio','Other Mac'],
 [key('Computer Repair','Windows PC')]:['Windows Laptop','Windows Desktop','Gaming Laptop','Gaming Desktop','All-in-One PC','Other Windows PC'],
 [key('Computer Repair','Chromebook')]:['Acer Chromebook','ASUS Chromebook','HP Chromebook','Lenovo Chromebook','Samsung Chromebook','Other Chromebook'],
 [key('Computer Repair','Other')]:['Linux Computer','Custom Computer','Other Computer'],
 [key('Game Console Repair','PlayStation')]:['PS5 Pro','PS5 Slim','PS5','PS4 Pro','PS4 Slim','PS4'],
 [key('Game Console Repair','Xbox')]:['Xbox Series X','Xbox Series S','Xbox One X','Xbox One S','Xbox One'],
 [key('Game Console Repair','Nintendo')]:['Nintendo Switch OLED','Nintendo Switch','Switch Lite','Wii U','Other Nintendo'],
 [key('Game Console Repair','Other')]:['Steam Deck','ROG Ally','Other Game Console'],
 [key('Apple Watch Repair','Apple')]:['Apple Watch Ultra 2','Apple Watch Ultra','Apple Watch Series 10','Apple Watch Series 9','Apple Watch Series 8','Apple Watch Series 7','Apple Watch Series 6','Apple Watch Series 5','Apple Watch Series 4','Apple Watch SE 2','Apple Watch SE','Other Apple Watch'],
 [key('Quick Check-in','General Device')]:['Other Device']
};
const SERVICES=['Screen Replacement','Battery Replacement','Charging Port','Back Glass / Housing','Camera','Speaker / Microphone','Keyboard / Trackpad','Software / Data','Board Repair','Diagnostic','Water Damage','Other Repair'];
const STATUSES:RepairStatus[]=['Checked In','Diagnosing','Waiting on Parts','Repairing','Ready for Pickup'];
const CHECKLIST=['Powers on','Display works','Touch works','Cameras work','Speakers work','Microphone works','Charging works','Wi-Fi/Bluetooth works','Face ID / Touch ID works','No liquid damage visible'];
function freshCatalog():Catalog{const brands:Record<string,Entry[]>={},models:Record<string,Entry[]>={},services:Record<string,Entry[]>={};CATEGORIES.forEach(c=>brands[c]=entries(BRANDS[c]||['Other']));Object.entries(MODELS).forEach(([k,v])=>models[k]=entries(v));return{categories:entries(CATEGORIES),brands,models,services}}
function loadCatalog():Catalog{try{const saved=JSON.parse(localStorage.getItem('gadgetpos_repair_catalog_v2')||'null');if(saved?.categories)return saved}catch{}return freshCatalog()}

export default function RepairIntakeWidgetV2(){
 const [catalog,setCatalog]=useState<Catalog>(loadCatalog),[open,setOpen]=useState(false),[step,setStep]=useState<Step>('brand'),[createdRepair,setCreatedRepair]=useState<Repair|null>(null);
 const [category,setCategory]=useState(''),[brand,setBrand]=useState(''),[model,setModel]=useState(''),[service,setService]=useState(''),[partId,setPartId]=useState(''),[search,setSearch]=useState('');
 const [manager,setManager]=useState<ManageLevel|null>(null),[managerText,setManagerText]=useState(''),[editingId,setEditingId]=useState('');
 const [customerName,setCustomerName]=useState(''),[customerPhone,setCustomerPhone]=useState(''),[imei,setImei]=useState(''),[passcode,setPasscode]=useState(''),[warranty,setWarranty]=useState('30 Day Store Warranty'),[checkedInBy,setCheckedInBy]=useState('Rodney'),[technician,setTechnician]=useState('Rodney'),[status,setStatus]=useState<RepairStatus>('Checked In'),[notes,setNotes]=useState(''),[checked,setChecked]=useState<string[]>([]);
 const inventory=storage.getInventory();
 const parts=useMemo(()=>inventory.filter(i=>i.category==='Repair Part'&&i.quantity>0),[open,inventory.length]);
 const matchingParts=useMemo(()=>parts.filter(part=>{
  const structured=Boolean(part.repairDeviceType||part.compatibleBrands?.length||part.compatibleModels?.length||part.compatibleRepairTypes?.length);
  if(structured)return (!part.repairDeviceType||norm(part.repairDeviceType)===norm(category))&&(!part.compatibleBrands?.length||part.compatibleBrands.some(x=>norm(x)===norm(brand)))&&(!part.compatibleModels?.length||part.compatibleModels.some(x=>norm(x)===norm(model)))&&(!part.compatibleRepairTypes?.length||part.compatibleRepairTypes.some(x=>norm(x)===norm(service)));
  const hay=[part.name,part.model,part.notes,part.sku].join(' ').toLowerCase();
  return Boolean(model)&&hay.includes(norm(model));
 }).sort((a,b)=>a.price-b.price||a.name.localeCompare(b.name)),[parts,category,brand,model,service]);
 const selectedPart=parts.find(p=>p.id===partId);
 useEffect(()=>{const click=(e:MouseEvent)=>{const button=(e.target as HTMLElement).closest('button');const text=button?.textContent||'';const match=catalog.categories.find(c=>!c.hidden&&text.includes(c.name));if(match){setCategory(match.name);setBrand('');setModel('');setService('');setPartId('');setStep('brand');setSearch('');setOpen(true)}};document.addEventListener('click',click);return()=>document.removeEventListener('click',click)},[catalog]);
 function save(next:Catalog){setCatalog(next);localStorage.setItem('gadgetpos_repair_catalog_v2',JSON.stringify(next))}
 function listFor(level:ManageLevel):Entry[]{if(level==='category')return catalog.categories;if(level==='brand')return catalog.brands[category]||[];if(level==='model')return catalog.models[key(category,brand)]||[];return catalog.services[key(category,brand,model)]||entries(SERVICES)}
 function setList(level:ManageLevel,list:Entry[]){const next={...catalog,brands:{...catalog.brands},models:{...catalog.models},services:{...catalog.services}};if(level==='category')next.categories=list;else if(level==='brand')next.brands[category]=list;else if(level==='model')next.models[key(category,brand)]=list;else next.services[key(category,brand,model)]=list;save(next)}
 function visible(level:ManageLevel){const q=search.toLowerCase();return listFor(level).filter(x=>!x.hidden&&x.name.toLowerCase().includes(q))}
 function openManager(level:ManageLevel){setManager(level);setManagerText('');setEditingId('')}
 function saveManagerItem(){if(!manager||!managerText.trim())return;const list=listFor(manager);setList(manager,editingId?list.map(x=>x.id===editingId?{...x,name:managerText.trim()}:x):[...list,{id:uid(),name:managerText.trim()}]);setManagerText('');setEditingId('')}
 function move(level:ManageLevel,index:number,delta:number){const list=[...listFor(level)],next=index+delta;if(next<0||next>=list.length)return;[list[index],list[next]]=[list[next],list[index]];setList(level,list)}
 function reset(){setOpen(false);setStep('brand');setCategory('');setBrand('');setModel('');setService('');setPartId('');setSearch('')}
 function back(){setSearch('');setStep(step==='final'?'part':step==='part'?'service':step==='service'?'model':'brand')}
 function choosePart(part:InventoryItem){setPartId(part.id);if(part.warranty)setWarranty(part.warranty);setStep('final')}
 function createTicket(){if(!customerName.trim()||!customerPhone.trim()||!brand||!model||!service){alert('Please complete the customer, brand, model, and repair fields.');return}const repairs=storage.getRepairs(),now=new Date().toISOString(),next=Math.max(0,...repairs.map(r=>Number(r.number.replace(/\D/g,''))||0))+1;const repair:Repair={id:uid(),number:`R-${String(next).padStart(5,'0')}`,customerId:'walk-in',customerName:customerName.trim(),customerPhone:customerPhone.trim(),deviceType:category,brand,model,serial:imei,passcode,issue:service,part:selectedPart?.name,partId:selectedPart?.id,status,technician,priority:'Normal',estimate:selectedPart?.price||0,createdAt:now,notes:[`Warranty: ${warranty}`,selectedPart?.supplier?`Supplier: ${selectedPart.supplier}`:'',selectedPart?.location?`Part location: ${selectedPart.location}`:'',`Checked in by: ${checkedInBy}`,`Checklist: ${checked.join(', ')||'Not completed'}`,notes].filter(Boolean).join('\n')};storage.saveRepairs([repair,...repairs]);window.dispatchEvent(new Event('gadgetpos-data-changed'));setOpen(false);setCreatedRepair(repair);setCustomerName('');setCustomerPhone('');setImei('');setPasscode('');setNotes('');setChecked([])}
 function printTicket(r:Repair){const frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:1px;height:1px;opacity:0;border:0';document.body.appendChild(frame);const d=frame.contentWindow?.document;if(!d)return;d.open();d.write(`<html><head><style>body{font-family:Arial;color:#17283a;padding:30px}h1{border-bottom:4px solid #2678c9;padding-bottom:10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.box{border:1px solid #ccd7e0;padding:12px;border-radius:8px}.full{grid-column:1/-1}.sig{margin-top:60px;border-top:1px solid #222;width:45%}</style></head><body><h1>Gadget Defenders</h1><h2>${r.number}</h2><p>203 Burkesville St, Suite 121 · Columbia, KY · 270-380-1505</p><div class="grid"><div class="box"><b>Customer</b><br>${r.customerName}</div><div class="box"><b>Phone</b><br>${r.customerPhone}</div><div class="box"><b>Device</b><br>${r.brand} ${r.model}</div><div class="box"><b>IMEI/Serial</b><br>${r.serial||'—'}</div><div class="box full"><b>Repair</b><br>${r.issue}</div><div class="box"><b>Part</b><br>${r.part||'None'}</div><div class="box"><b>Estimate</b><br>$${r.estimate.toFixed(2)}</div><div class="box full"><b>Notes</b><br>${(r.notes||'—').replace(/\n/g,'<br>')}</div></div><div class="sig">Customer Signature / Date</div></body></html>`);d.close();setTimeout(()=>{frame.contentWindow?.print();setTimeout(()=>frame.remove(),1500)},250)}
 const currentLevel:ManageLevel=step==='brand'?'brand':step==='model'?'model':'service';
 const title=manager==='category'?'Repair Categories':manager==='brand'?`Manufacturers inside ${category}`:manager==='model'?`Models inside ${category} › ${brand}`:`Repairs inside ${model}`;
 return <>
  <button className="repair-admin-button" onClick={()=>openManager('category')}><Settings2 size={16}/>Repair Catalog</button>
  {open&&<div className="ri-backdrop"><div className="ri-modal"><div className="ri-head"><div><h2>{category}</h2><p>{[category,brand,model,service].filter(Boolean).join(' › ')}</p></div><button onClick={reset}><X/></button></div>{step!=='brand'&&<button className="ri-back" onClick={back}><ArrowLeft size={16}/>Back</button>}{step!=='part'&&step!=='final'&&<div className="ri-level-tools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${step==='brand'?'manufacturers':step==='model'?'models':'repairs'}...`}/><button onClick={()=>openManager(currentLevel)}><Settings2 size={16}/>Manage This Level</button></div>}
   {step==='brand'&&<div className="ri-choice-grid">{visible('brand').map(x=><button key={x.id} onClick={()=>{setBrand(x.name);setSearch('');setStep('model')}}><strong>{x.name}</strong><small>Choose manufacturer</small></button>)}</div>}
   {step==='model'&&<div className="ri-choice-grid">{visible('model').map(x=><button key={x.id} onClick={()=>{setModel(x.name);setSearch('');setStep('service')}}><strong>{x.name}</strong><small>Select {category.replace(' Repair','').toLowerCase()} model</small></button>)}</div>}
   {step==='service'&&<div className="ri-choice-grid">{visible('service').map(x=><button key={x.id} onClick={()=>{setService(x.name);setPartId('');setStep('part')}}><strong>{x.name}</strong><small>Select repair</small></button>)}</div>}
   {step==='part'&&<div><div className="ri-part-head"><div><h3>Compatible Inventory Parts</h3><p>{brand} · {model} · {service}</p></div><button onClick={()=>setStep('final')}>Continue Without Part</button></div><div className="ri-part-list">{matchingParts.map(p=><button key={p.id} onClick={()=>choosePart(p)}><div><strong>{p.name}</strong><small>{[p.sku,p.warranty,p.supplier,p.location].filter(Boolean).join(' · ')||'Tagged repair part'}</small></div><div><span>{p.quantity} in stock</span><b>${p.price.toFixed(2)}</b></div></button>)}{!matchingParts.length&&<div className="ri-no-parts"><strong>No compatible parts found.</strong><span>Tag an inventory part to {category}, {brand}, {model}, and {service}, or continue without a part.</span></div>}</div></div>}
   {step==='final'&&<div className="ri-final"><h3>Complete Repair Check-In</h3><div className="ri-selected"><strong>{brand} {model}</strong><span>{service}{selectedPart?` · ${selectedPart.name} · ${selectedPart.quantity} in stock`:''}</span></div><div className="ri-grid"><label>Customer name<input value={customerName} onChange={e=>setCustomerName(e.target.value)}/></label><label>Phone<input value={customerPhone} onChange={e=>setCustomerPhone(e.target.value)}/></label><label>IMEI / Serial<input value={imei} onChange={e=>setImei(e.target.value)}/></label><label>Passcode<input value={passcode} onChange={e=>setPasscode(e.target.value)}/></label><label>Warranty<select value={warranty} onChange={e=>setWarranty(e.target.value)}><option>Lifetime Screen Warranty</option><option>90 Day Store Warranty</option><option>30 Day Store Warranty</option><option>No Warranty</option></select></label><label>Technician<input value={technician} onChange={e=>setTechnician(e.target.value)}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value as RepairStatus)}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></label><label>Checked in by<input value={checkedInBy} onChange={e=>setCheckedInBy(e.target.value)}/></label></div><div className="ri-checklist"><strong>Device checklist</strong>{CHECKLIST.map(x=><label key={x}><input type="checkbox" checked={checked.includes(x)} onChange={()=>setChecked(checked.includes(x)?checked.filter(y=>y!==x):[...checked,x])}/>{x}</label>)}</div><label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="ri-actions"><button onClick={reset}>Cancel</button><button className="primary" onClick={createTicket}>Create Repair Ticket</button></div></div>}
  </div></div>}
  {manager&&<div className="ri-backdrop ri-manager-layer"><div className="ri-modal small"><div className="ri-head"><div><h2>{title}</h2><p>Add, rename, reorder, hide, or delete choices.</p></div><button onClick={()=>setManager(null)}><X/></button></div><div className="ri-manager-list">{listFor(manager).map((x,index)=><div key={x.id} className={x.hidden?'hidden':''}><span>{x.name}</span><div><button onClick={()=>move(manager,index,-1)}><ArrowUp size={15}/></button><button onClick={()=>move(manager,index,1)}><ArrowDown size={15}/></button><button onClick={()=>{setEditingId(x.id);setManagerText(x.name)}}><Pencil size={15}/></button><button onClick={()=>setList(manager,listFor(manager).map(y=>y.id===x.id?{...y,hidden:!y.hidden}:y))}>{x.hidden?<Eye size={15}/>:<EyeOff size={15}/>}</button><button onClick={()=>setList(manager,listFor(manager).filter(y=>y.id!==x.id))}><Trash2 size={15}/></button></div></div>)}</div><div className="ri-add"><input value={managerText} onChange={e=>setManagerText(e.target.value)} placeholder="New or edited name"/><button className="primary" onClick={saveManagerItem}><Plus size={16}/>{editingId?'Save':'Add'}</button></div></div></div>}
  {createdRepair&&<div className="ri-backdrop"><div className="ri-modal small"><div className="ri-head"><div><h2>Ticket Created</h2><p>{createdRepair.number} · {createdRepair.customerName}</p></div><button onClick={()=>setCreatedRepair(null)}><X/></button></div><div className="ri-actions"><button onClick={()=>printTicket(createdRepair)}><Printer size={16}/>Print Ticket</button><button className="primary" onClick={()=>{window.dispatchEvent(new CustomEvent('gadgetpos-add-repair',{detail:{repairId:createdRepair.id}}));setCreatedRepair(null)}}><ShoppingCart size={16}/>Add to Checkout</button></div></div></div>}
 </>
}
