import { useEffect, useMemo, useState } from 'react';
import { Search, ShieldCheck, X } from 'lucide-react';
import { storage } from './storage';
import type { Repair } from './types';

type WarrantyRecord={id:string;repairId:string;type:string;startsAt:string;endsAt?:string;status:'Active'|'Expired'|'Claim Open'|'Closed';notes?:string;claims:{id:string;date:string;issue:string;resolution?:string;status:'Open'|'Closed'}[]};
const KEY='gadgetpos_warranties_v1';
const read=():WarrantyRecord[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const save=(rows:WarrantyRecord[])=>localStorage.setItem(KEY,JSON.stringify(rows));

export default function WarrantyCenterWidget(){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[records,setRecords]=useState<WarrantyRecord[]>(read()),[selected,setSelected]=useState<Repair|null>(null),[type,setType]=useState('Lifetime Parts Warranty'),[months,setMonths]=useState(''),[notes,setNotes]=useState(''),[claimIssue,setClaimIssue]=useState('');
 const repairs=storage.getRepairs();
 useEffect(()=>{const nav=document.querySelector('.sidebar nav');if(!nav||document.getElementById('gadgetpos-warranty-nav'))return;const b=document.createElement('button');b.id='gadgetpos-warranty-nav';b.innerHTML='<span>🛡️</span><span>Warranties</span>';b.onclick=()=>setOpen(true);nav.appendChild(b);const wire=()=>document.querySelectorAll<HTMLElement>('.repair-card').forEach(card=>{if(card.dataset.warrantyReady)return;const ticket=card.querySelector('strong')?.textContent?.trim();if(!ticket)return;const btn=document.createElement('button');btn.className='warranty-card-button';btn.textContent='Warranty';btn.onclick=e=>{e.stopPropagation();const r=storage.getRepairs().find(x=>x.number===ticket);if(r){setSelected(r);setOpen(true)}};card.appendChild(btn);card.dataset.warrantyReady='1'});wire();const o=new MutationObserver(wire);o.observe(document.body,{subtree:true,childList:true});return()=>{b.remove();o.disconnect()}},[]);
 const rows=useMemo(()=>repairs.filter(r=>[r.number,r.customerName,r.customerPhone,r.brand,r.model,r.issue].join(' ').toLowerCase().includes(query.toLowerCase())),[repairs,query]);
 const recordFor=(id:string)=>records.find(w=>w.repairId===id);
 function createWarranty(r:Repair){const start=new Date();const end=months?new Date(start.getFullYear(),start.getMonth()+Number(months),start.getDate()).toISOString():undefined;const next=[...records.filter(w=>w.repairId!==r.id),{id:crypto.randomUUID(),repairId:r.id,type,startsAt:start.toISOString(),endsAt:end,status:'Active' as const,notes,claims:[]}];setRecords(next);save(next);}
 function startClaim(r:Repair){if(!claimIssue.trim())return;let rec=recordFor(r.id);if(!rec){createWarranty(r);rec={id:crypto.randomUUID(),repairId:r.id,type,startsAt:new Date().toISOString(),status:'Active',notes,claims:[]}}const next=records.filter(w=>w.repairId!==r.id);const updated={...rec,status:'Claim Open' as const,claims:[...rec.claims,{id:crypto.randomUUID(),date:new Date().toISOString(),issue:claimIssue.trim(),status:'Open' as const}]};setRecords([...next,updated]);save([...next,updated]);setClaimIssue('');}
 function closeClaim(w:WarrantyRecord,id:string){const updated={...w,status:'Active' as const,claims:w.claims.map(c=>c.id===id?{...c,status:'Closed' as const,resolution:'Resolved'}:c)};const next=records.map(x=>x.id===w.id?updated:x);setRecords(next);save(next)}
 return <>{open&&<div className="warranty-overlay"><header><div><h1>Warranty Center</h1><p>Coverage, claims, and repair return history</p></div><button onClick={()=>setOpen(false)}><X/></button></header><div className="warranty-toolbar"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ticket, customer, phone, or device"/></label></div><div className="warranty-layout"><section className="warranty-list">{rows.map(r=>{const w=recordFor(r.id);return <button key={r.id} className={selected?.id===r.id?'active':''} onClick={()=>setSelected(r)}><span><strong>{r.number} · {r.customerName}</strong><small>{r.brand} {r.model} · {r.issue}</small></span><b className={w?'covered':'none'}>{w?.status||'No Warranty'}</b></button>})}</section><section className="warranty-detail">{selected?(()=>{const w=recordFor(selected.id);return <><div className="warranty-hero"><ShieldCheck/><div><h2>{selected.number}</h2><p>{selected.customerName} · {selected.brand} {selected.model}</p></div></div><div className="warranty-grid"><label>Warranty Type<select value={type} onChange={e=>setType(e.target.value)}><option>Lifetime Parts Warranty</option><option>90 Day Warranty</option><option>30 Day Warranty</option><option>No Warranty</option></select></label><label>Coverage Months<input type="number" min="0" value={months} onChange={e=>setMonths(e.target.value)} placeholder="Blank = lifetime"/></label><label className="full">Warranty Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Coverage exceptions or internal notes"/></label></div><button className="primary" onClick={()=>createWarranty(selected)}>{w?'Update Warranty':'Create Warranty'}</button>{w&&<div className="warranty-summary"><div><span>Status</span><strong>{w.status}</strong></div><div><span>Started</span><strong>{new Date(w.startsAt).toLocaleDateString()}</strong></div><div><span>Ends</span><strong>{w.endsAt?new Date(w.endsAt).toLocaleDateString():'Lifetime'}</strong></div></div>}<div className="claim-box"><h3>Start Warranty Claim</h3><textarea value={claimIssue} onChange={e=>setClaimIssue(e.target.value)} placeholder="Describe the customer’s warranty issue"/><button onClick={()=>startClaim(selected)}>Open Claim</button></div>{w?.claims.length? <div className="claim-history"><h3>Claim History</h3>{w.claims.slice().reverse().map(c=><article key={c.id}><div><strong>{c.issue}</strong><small>{new Date(c.date).toLocaleString()} · {c.status}</small></div>{c.status==='Open'&&<button onClick={()=>closeClaim(w,c.id)}>Close Claim</button>}</article>)}</div>:null}</>})():<div className="warranty-empty">Select a repair to manage its warranty.</div>}</section></div></div>}</>;
}
